version: "3.1"
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: minha_base
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/data/postgres

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_CONFIG_SESSION_EXPIRATION_TIME: "365"
      PGADMIN_MASTER_PASSWORD_REQUIRED: "false"
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - 8085:80
#    volumes:
#      - ./pgadmin.json:/pgadmin4/servers.json:ro

networks:
  default:
    external:
      name: web

volumes:
  postgres: